
all:
	make -C 2mm
	make -C 3mm
	make -C atax
	make -C bicg
#	make -C cholesky
#	make -C doitgen
#	make -C gemm
#	make -C gemver
#	make -C gesummv
#	make -C mvt
#	make -C symm
#	make -C syr2k
#	make -C syrk
#	make -C trisolv
#	make -C trmm

